job('FirstJobDsl'){
	description("this is job generated by DSL job")
	scm{
		git("https://github.com/mohamed-elhar/webApp.git","master")
	}
	triggers{
		scm("* * * * *")
	}
	steps{
		maven("clean package")
	}
	publishers{
		archiveArtifacts "**/webApp.war"
	}
}
